
package org.dlbc.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebService(name = "NIWebServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NIWebServiceSoap {


    /**
     * 根据献血码获取检验结果网上查询验证码。
     * 
     * @param donCode
     * @return
     *     returns org.dlbc.ws.NetSearchTestResultInfo
     */
    @WebMethod(operationName = "GetTestResultSearchVerifyCodeByDonCode", action = "http://tempuri.org/GetTestResultSearchVerifyCodeByDonCode")
    @WebResult(name = "GetTestResultSearchVerifyCodeByDonCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTestResultSearchVerifyCodeByDonCode", targetNamespace = "http://tempuri.org/", className = "org.dlbc.ws.GetTestResultSearchVerifyCodeByDonCode")
    @ResponseWrapper(localName = "GetTestResultSearchVerifyCodeByDonCodeResponse", targetNamespace = "http://tempuri.org/", className = "org.dlbc.ws.GetTestResultSearchVerifyCodeByDonCodeResponse")
    public NetSearchTestResultInfo getTestResultSearchVerifyCodeByDonCode(
        @WebParam(name = "donCode", targetNamespace = "http://tempuri.org/")
        String donCode);

    /**
     * 根据献血码、验证码从网站获取检验最终结论。
     * 
     * @param verifyCode
     * @param donCode
     * @return
     *     returns org.dlbc.ws.NetSearchTestResultInfo
     */
    @WebMethod(operationName = "GetTestResultByDonCode", action = "http://tempuri.org/GetTestResultByDonCode")
    @WebResult(name = "GetTestResultByDonCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTestResultByDonCode", targetNamespace = "http://tempuri.org/", className = "org.dlbc.ws.GetTestResultByDonCode")
    @ResponseWrapper(localName = "GetTestResultByDonCodeResponse", targetNamespace = "http://tempuri.org/", className = "org.dlbc.ws.GetTestResultByDonCodeResponse")
    public NetSearchTestResultInfo getTestResultByDonCode(
        @WebParam(name = "donCode", targetNamespace = "http://tempuri.org/")
        String donCode,
        @WebParam(name = "verifyCode", targetNamespace = "http://tempuri.org/")
        String verifyCode);

    /**
     * 根据证件类型、证件号码获取检验结果验证码。
     * 
     * @param idCode
     * @param idTypeID
     * @return
     *     returns org.dlbc.ws.NetSearchTestResultInfo
     */
    @WebMethod(operationName = "GetTestResultSearchVerifyCodeByIdCode", action = "http://tempuri.org/GetTestResultSearchVerifyCodeByIdCode")
    @WebResult(name = "GetTestResultSearchVerifyCodeByIdCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTestResultSearchVerifyCodeByIdCode", targetNamespace = "http://tempuri.org/", className = "org.dlbc.ws.GetTestResultSearchVerifyCodeByIdCode")
    @ResponseWrapper(localName = "GetTestResultSearchVerifyCodeByIdCodeResponse", targetNamespace = "http://tempuri.org/", className = "org.dlbc.ws.GetTestResultSearchVerifyCodeByIdCodeResponse")
    public NetSearchTestResultInfo getTestResultSearchVerifyCodeByIdCode(
        @WebParam(name = "idTypeID", targetNamespace = "http://tempuri.org/")
        String idTypeID,
        @WebParam(name = "idCode", targetNamespace = "http://tempuri.org/")
        String idCode);

    /**
     * 根据证件类型、证件号码、验证码获取检验结果。
     * 
     * @param verifyCode
     * @param idCode
     * @param idTypeID
     * @return
     *     returns org.dlbc.ws.NetSearchTestResultInfo
     */
    @WebMethod(operationName = "GetTestResultByIdCode", action = "http://tempuri.org/GetTestResultByIdCode")
    @WebResult(name = "GetTestResultByIdCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTestResultByIdCode", targetNamespace = "http://tempuri.org/", className = "org.dlbc.ws.GetTestResultByIdCode")
    @ResponseWrapper(localName = "GetTestResultByIdCodeResponse", targetNamespace = "http://tempuri.org/", className = "org.dlbc.ws.GetTestResultByIdCodeResponse")
    public NetSearchTestResultInfo getTestResultByIdCode(
        @WebParam(name = "idTypeID", targetNamespace = "http://tempuri.org/")
        String idTypeID,
        @WebParam(name = "idCode", targetNamespace = "http://tempuri.org/")
        String idCode,
        @WebParam(name = "verifyCode", targetNamespace = "http://tempuri.org/")
        String verifyCode);

    /**
     * 验证网上预约人员是否满足献血要求。
     * 
     * @param birthday
     * @param sexID
     * @param name
     * @param idCode
     * @param idTypeID
     * @return
     *     returns org.dlbc.ws.NetAppReturnInfo
     */
    @WebMethod(operationName = "CheckAppArchives", action = "http://tempuri.org/CheckAppArchives")
    @WebResult(name = "CheckAppArchivesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CheckAppArchives", targetNamespace = "http://tempuri.org/", className = "org.dlbc.ws.CheckAppArchives")
    @ResponseWrapper(localName = "CheckAppArchivesResponse", targetNamespace = "http://tempuri.org/", className = "org.dlbc.ws.CheckAppArchivesResponse")
    public NetAppReturnInfo checkAppArchives(
        @WebParam(name = "idTypeID", targetNamespace = "http://tempuri.org/")
        String idTypeID,
        @WebParam(name = "idCode", targetNamespace = "http://tempuri.org/")
        String idCode,
        @WebParam(name = "name", targetNamespace = "http://tempuri.org/")
        String name,
        @WebParam(name = "sexID", targetNamespace = "http://tempuri.org/")
        String sexID,
        @WebParam(name = "birthday", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar birthday);

    /**
     * 验证网上预约信息是否满足献血间隔。
     * 
     * @param birthday
     * @param appStartDate
     * @param sexID
     * @param name
     * @param idCode
     * @param appEndDate
     * @param donKindID
     * @param idTypeID
     * @return
     *     returns org.dlbc.ws.NetAppReturnInfo
     */
    @WebMethod(operationName = "CheckAppInterval", action = "http://tempuri.org/CheckAppInterval")
    @WebResult(name = "CheckAppIntervalResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CheckAppInterval", targetNamespace = "http://tempuri.org/", className = "org.dlbc.ws.CheckAppInterval")
    @ResponseWrapper(localName = "CheckAppIntervalResponse", targetNamespace = "http://tempuri.org/", className = "org.dlbc.ws.CheckAppIntervalResponse")
    public NetAppReturnInfo checkAppInterval(
        @WebParam(name = "idTypeID", targetNamespace = "http://tempuri.org/")
        String idTypeID,
        @WebParam(name = "idCode", targetNamespace = "http://tempuri.org/")
        String idCode,
        @WebParam(name = "name", targetNamespace = "http://tempuri.org/")
        String name,
        @WebParam(name = "sexID", targetNamespace = "http://tempuri.org/")
        String sexID,
        @WebParam(name = "birthday", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar birthday,
        @WebParam(name = "donKindID", targetNamespace = "http://tempuri.org/")
        String donKindID,
        @WebParam(name = "appStartDate", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar appStartDate,
        @WebParam(name = "appEndDate", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar appEndDate);

    /**
     * 审核通过后上传预约记录信息。
     * 
     * @param netAppRecordInfo
     * @return
     *     returns org.dlbc.ws.NetAppReturnInfo
     */
    @WebMethod(operationName = "InsertAppInfo", action = "http://tempuri.org/InsertAppInfo")
    @WebResult(name = "InsertAppInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InsertAppInfo", targetNamespace = "http://tempuri.org/", className = "org.dlbc.ws.InsertAppInfo")
    @ResponseWrapper(localName = "InsertAppInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.dlbc.ws.InsertAppInfoResponse")
    public NetAppReturnInfo insertAppInfo(
        @WebParam(name = "netAppRecordInfo", targetNamespace = "http://tempuri.org/")
        NetAppRecordInfo netAppRecordInfo);

    /**
     * 获取本血站的采血地点列表。
     * 
     * @return
     *     returns org.dlbc.ws.ArrayOfCollectPlaceDic
     */
    @WebMethod(operationName = "GetCollectPlaceList", action = "http://tempuri.org/GetCollectPlaceList")
    @WebResult(name = "GetCollectPlaceListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCollectPlaceList", targetNamespace = "http://tempuri.org/", className = "org.dlbc.ws.GetCollectPlaceList")
    @ResponseWrapper(localName = "GetCollectPlaceListResponse", targetNamespace = "http://tempuri.org/", className = "org.dlbc.ws.GetCollectPlaceListResponse")
    public ArrayOfCollectPlaceDic getCollectPlaceList();

}
